name: pkgdown (metahub)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'metahub/**'
      - '.github/workflows/pkgdown-metahub.yml'
  workflow_dispatch:

# Top-level permissions for Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only one Pages deployment at a time
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install R deps for metahub
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: metahub
          extra-packages: |
            any::pkgdown
            local::.
          needs: website
      - name: Build pkgdown site
        working-directory: metahub
        run: Rscript -e "pkgdown::build_site(preview = FALSE)"
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: metahub/docs
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
