name: pkgdown (metahub)

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'metahub/**'
      - '.github/workflows/pkgdown-metahub.yml'
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: metahub
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            local::.
      - name: Build site
        run: Rscript -e 'pkgdown::build_site()'
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: metahub/docs
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
