
name: pkgdown (metahub)
on:
  push:
    branches: [ master ]
    paths:
      - "metahub/**"
      - ".github/workflows/pkgdown-metahub.yml"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: metahub
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website
      - name: Build site
        run: pkgdown::build_site(preview = false)
        shell: Rscript {0}
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: metahub/docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

